### ISSUE TITLE
Remove bitcoins when building/upgrading a tower.

### ISSUE THREAD

**Issue by spinspume** [juleskreutzer/PTS3#19]

**Comment by martiener1** [comment]
The coding looks like it's right.
The database probably contains '0.0' as cost.

**Comment by juleskreutzer** [comment]
Correct, will change the cost of some modules in a minute

**Comment by juleskreutzer** [comment]
<img width="155" alt="bitcoins" src="https://cloud.githubusercontent.com/assets/9107254/10846069/08392ca6-7f0d-11e5-9fa4-7193a92cec11.png">
Changed data in database, now works
