### ISSUE TITLE
SoftwareInjector cannot add spells (missing data class).

### ISSUE THREAD

**Issue by spinspume** [juleskreutzer/PTS3#24]
Is softwareInjector supposed to implement a data class?
Else find workaround.

**Comment by juleskreutzer** [comment]
When the upgrade Method of the software injector is called, it add 3 spells to the list "spells". (this could be changed so each spell will be added to "spellList", don't know why we have 2 lists)

When the Software Injector is upgraded to level 2, the following spells will become available:
- Corrupt
- Lockdown
- Firewall

On level 3, the following spells will become available:
- Disrupt
- Encrypt
- Virusscan

Where did you get the error?

**Comment by spinspume** [comment]
When running the unittest for upgrarding the SoftwareInjector the spell = new spell part throws an error.
I think it's because the spellTemplate equals null because there's no data class but not sure.
