### ISSUE TITLE
Towers don't target minions from the last wave when a new wave has started

### ISSUE THREAD

**Issue by JasperRh** [juleskreutzer/PTS3#25]
When a new wave is starting while the last hasn't end, the modules wont attack the minions from the last wave.

This is because in the Defense.findTarget() the module is iterating trough the minionlist of the current wave

**Comment by martiener1** [comment]
Fixed on branch "martijnBranch" with commit: 4953138d37d4e5716c66c289d71e922630f70246.

**Comment by martiener1** [comment]
Maybe it's more performance efficient to make another field in gameEngine that only contains the active waves.
